### ISSUE TITLE
Random skip in downloaded tracks

### ISSUE THREAD

**Issue by tr33s** [vitiko98/qobuz-dl#184]
Just started using this tool and noticed that some tracks have a random pause/skip in them. Strangely, it persists in the same location even on re-download. The track length isn't affected, so just wondering if anyone has any ideas why this is occurring?

**Comment by pingzoo** [comment]
Yes, it's the same for me. But this also happens if you do not use qobuz-dl but e.g. another provider that uses the API of Qobuz.

I've found in 2-3 short tests that these skips happen when playing with the player VLC. I have not yet noticed these skips with Groove Music (Win10).

So I suspect it's not qobuz-dl, but Qobuz or VLC. But I am not sure.

**Comment by tr33s** [comment]
@pingzoo That is strange. Yes, noticeable in VLC, but does not occur in KMPlayer or playing from Chrome browser. How strange. Thanks!

**Comment by pingzoo** [comment]
Oh you are welcome. It reassured me to see that it wasn't just me.
I've made several tests today, just to be sure.
It's an VLC issue with decoding and buffering of "big" flac files.
