### ISSUE TITLE
Download purchased songs without subscription

### ISSUE THREAD

**Issue by xeruf** [vitiko98/qobuz-dl#230]
Hey, I buy songs/albums individually rather than subscribing, can I download them with this application as well?
Since they retired tar downloading in the web this is otherwise quite annoying, as the downloader is not available for Linux...

**Comment by morphismz** [comment]
I've been having the same question. When I try to download a purchased album, I get the error "Free accounts are not eligible to download tracks". 

So it seems that `qobuz-dl` does not currently support downloading purchased albums. This is quite annoying, especially for linux users, since the only other option is downloading each song individually...

It would be very nice to have this added as a feature.

**Comment by xeruf** [comment]
I have been thinking that maybe after all the subscription is more affordable, since you can just download everything with it in the same quality like buying it seems?

**Comment by Pedro-Montanari** [comment]
I find myself with the same problem, I bought albums on Qobuz without the subscription. I tried installing Qobuz Downloader with Bottles on Ubuntu, but without much success. So qobuz-dl seems the most viable reason for the moment to use it on Linux.

**Comment by xeruf** [comment]
Went for the subscription now, much more sensible financially and with this tool
